# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogout():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_logOut(self):
    self.driver.get("https://www.saucedemo.com/")
    self.driver.maximize_window()
    usernameInput = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]")
    usernameInput.click()
    usernameInput.send_keys("standard_user")
    passwordInput = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]")
    passwordInput.click()
    passwordInput.send_keys("secret_sauce")
    loginBtn = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]")
    loginBtn.click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "react-burger-menu-btn")))
    selectBtn = self.driver.find_element(By.ID, "react-burger-menu-btn")
    selectBtn.click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "logout_sidebar_link")))
    logoutBtn = self.driver.find_element(By.ID, "logout_sidebar_link")
    logoutBtn.click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".login_wrapper-inner")))
    self.driver.close()
  
