# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCheckout():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_checkout(self):
    self.driver.get("https://www.saucedemo.com/")
    self.driver.maximize_window()
    usernameInput = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]")
    usernameInput.click()
    usernameInput.send_keys("standard_user")
    passwordInput = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]")
    passwordInput.click()
    passwordInput.send_keys("secret_sauce")
    loginBtn = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]")
    loginBtn.click()
    WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.CSS_SELECTOR, "#inventory_container #inventory_container")))
    selectPrd = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-backpack\"]")
    selectPrd.click()
    WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.CSS_SELECTOR, "#inventory_container #inventory_container")))
    selectPrd2 = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-test.allthethings()-t-shirt-(red)\"]")
    selectPrd2.click()
    WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.CSS_SELECTOR, "#inventory_container #inventory_container")))
    goToCart = self.driver.find_element(By.LINK_TEXT, "2")
    goToCart.click()
    WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.CSS_SELECTOR, ".cart_item:nth-child(3) .item_pricebar")))
    removePrd = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"remove-sauce-labs-backpack\"]")
    removePrd.click()
    WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.CSS_SELECTOR, ".cart_footer")))
    checkOut = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"checkout\"]")
    checkOut.click()
    WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.ID, "checkout_info_container")))
  
